version: '3'
services:
  imap:
    environment:
      - REDIS_URL=redis://redis:6379
    build: .
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
  redis:
    image: "redis:alpine"
    networks:
      - backend
networks:
  frontend:
  backend: